// 多语言舰船数据
export const SHIPS_DATA = {
  en: [
    { name: "Shimakaze", type: "DD" },
    { name: "Harugumo", type: "DD" },
    { name: "Hayate", type: "DD" },
    { name: "Yamato", type: "BB" },
    { name: "Shikishima", type: "BB" },
    { name: "Bungo", type: "BB" },
    { name: "Yoshino", type: "CA" },
    { name: "Kitakami", type: "CA" },
    { name: "Zao", type: "CA" },
    { name: "Yodo", type: "CA" },
    { name: "Hakuryu", type: "CV" },
    { name: "Shinano", type: "CV" },
    { name: "Montana", type: "BB" },
    { name: "Vermont", type: "BB" },
    { name: "Louisiana", type: "BB" },
    { name: "Wisconsin", type: "BB" },
    { name: "Rhode Island", type: "BB" },
    { name: "Ohio", type: "BB" },
    { name: "Des Moines", type: "CA" },
    { name: "Worcester", type: "CA" },
    { name: "Salem", type: "CA" },
    { name: "Austin", type: "CA" },
    { name: "Puerto Rico", type: "CA" },
    { name: "Gearing", type: "DD" },
    { name: "Hull", type: "DD" },
    { name: "Forrest Sherman", type: "DD" },
    { name: "Somers", type: "DD" },
    { name: "Midway", type: "CV" },
    { name: "Essex", type: "CV" },
    { name: "Franklin D. Roosevelt", type: "CV" },
    { name: "Balao", type: "SS" },
    { name: "Gato", type: "SS" },
    { name: "Archerfish", type: "SS" },
    { name: "Minotaur", type: "CA" },
    { name: "Daring", type: "DD" },
    { name: "St. Vincent", type: "BB" },
    { name: "Conqueror", type: "BB" },
    { name: "Thrasher", type: "SS" },
    { name: "Incomparable", type: "BB" },
    { name: "Plymouth", type: "CA" },
    { name: "Druid", type: "DD" },
    { name: "Audacious", type: "CV" },
    { name: "Monmouth", type: "CA" },
    { name: "Defense", type: "CA" },
    { name: "Malta", type: "CV" },
    { name: "Goliath", type: "CA" },
    { name: "Thunderer", type: "BB" },
    { name: "Seal", type: "SS" },
    { name: "Gibraltar", type: "CA" },
    { name: "Petropavlovsk", type: "CA" },
    { name: "K-1", type: "SS" },
    { name: "Khabarovsk", type: "DD" },
    { name: "Stalingrad", type: "CA" },
    { name: "Sevastopol", type: "CA" },
    { name: "Moskva", type: "CA" },
    { name: "Grozovoi", type: "DD" },
    { name: "Slava", type: "BB" },
    { name: "Kremlin", type: "BB" },
    { name: "Komissar", type: "CA" },
    { name: "Delny", type: "DD" },
    { name: "Nakhimov", type: "CV" },
    { name: "Alexander Nevsky", type: "CA" },
    { name: "Smolensk", type: "CA" },
    { name: "Hindenburg", type: "CA" },
    { name: "Grosser Kurfürst", type: "BB" },
    { name: "U-4501", type: "SS" },
    { name: "Elbing", type: "DD" },
    { name: "Z-42", type: "DD" },
    { name: "Schlieffen", type: "BB" },
    { name: "U-2501", type: "SS" },
    { name: "Hildebrand", type: "CA" },
    { name: "M. Richthofen", type: "CV" },
    { name: "Z-52", type: "DD" },
    { name: "Georg Hoffman", type: "DD" },
    { name: "Mecklenburg", type: "BB" },
    { name: "Max Immelmann", type: "CV" },
    { name: "Preussen", type: "BB" },
    { name: "Republique", type: "BB" },
    { name: "Cassard", type: "DD" },
    { name: "Marseille", type: "CA" },
    { name: "Colbert", type: "CA" },
    { name: "Kleber", type: "DD" },
    { name: "Bourgogne", type: "BB" },
    { name: "Brennus", type: "CA" },
    { name: "Henri IV", type: "CA" },
    { name: "Marceau", type: "DD" },
    { name: "Svea", type: "CA" },
    { name: "Småland", type: "DD" },
    { name: "Gdansk", type: "DD" },
    { name: "Ragnar", type: "DD" },
    { name: "Halland", type: "DD" },
    { name: "Attilio Regolo", type: "DD" },
    { name: "Venezia", type: "CA" },
    { name: "Alberico da Barbiano", type: "DD" },
    { name: "Ruggiero di Lauria", type: "BB" },
    { name: "Cristoforo Colombo", type: "BB" },
    { name: "Napoli", type: "CA" },
    { name: "Vampire II", type: "DD" },
    { name: "Cerberus", type: "CA" },
    { name: "Sicilia", type: "BB" },
    { name: "Brisbane", type: "CA" },
    { name: "Gouden Leeuw", type: "CA" },
    { name: "Yueyang", type: "DD" },
    { name: "Tromp", type: "DD" },
    { name: "Jinan", type: "CA" },
    { name: "Prins van Oranje", type: "CA" },
    { name: "La Pampa", type: "DD" },
    { name: "San Martín", type: "CA" },
    { name: "Álvaro de Bazán", type: "DD" },
    { name: "Incheon", type: "CA" },
    { name: "Lüshun", type: "DD" },
    { name: "Libertad", type: "DD" },
    { name: "Utrecht", type: "CA" },
    { name: "Castilla", type: "CA" },
    { name: "Willem de Eerste", type: "BB" },
    { name: "Irresistible", type: "BB" },
    { name: "Admiral Latgé", type: "CA" },
    { name: "Laffey", type: "DD" },
    { name: "Arrona's Beluga", type: "SS" },
    { name: "Siberia", type: "BB" },
    { name: "Yamato Kai", type: "BB" },
    { name: "Kushiro", type: "CA" },
    { name: "Prinz Adalbert", type: "CA" },
    { name: "Hawaii", type: "CA" },
    { name: "Bremen", type: "CA" },
    { name: "Aki", type: "BB" },
  ],
  zh: [
    { name: "岛风", type: "DD" },
    { name: "春云", type: "DD" },
    { name: "疾风", type: "DD" },
    { name: "大和", type: "BB" },
    { name: "敷岛", type: "BB" },
    { name: "丰后", type: "BB" },
    { name: "吉野", type: "CA" },
    { name: "北上", type: "CA" },
    { name: "藏王", type: "CA" },
    { name: "淀", type: "CA" },
    { name: "白龙", type: "CV" },
    { name: "信浓", type: "CV" },
    { name: "蒙大拿", type: "BB" },
    { name: "佛蒙特", type: "BB" },
    { name: "路易斯安那", type: "BB" },
    { name: "威斯康星", type: "BB" },
    { name: "罗德岛", type: "BB" },
    { name: "俄亥俄", type: "BB" },
    { name: "得梅因", type: "CA" },
    { name: "伍斯特", type: "CA" },
    { name: "塞勒姆", type: "CA" },
    { name: "奥斯汀", type: "CA" },
    { name: "波多黎各", type: "CA" },
    { name: "基林", type: "DD" },
    { name: "赫尔", type: "DD" },
    { name: "福雷斯特·谢尔曼", type: "DD" },
    { name: "萨默斯", type: "DD" },
    { name: "中途岛", type: "CV" },
    { name: "埃塞克斯", type: "CV" },
    { name: "富兰克林·罗斯福", type: "CV" },
    { name: "巴劳鱵", type: "SS" },
    { name: "猫鲨", type: "SS" },
    { name: "射水鱼", type: "SS" },
    { name: "米诺陶", type: "CA" },
    { name: "果敢", type: "DD" },
    { name: "圣文森特", type: "BB" },
    { name: "征服者", type: "BB" },
    { name: "连枷", type: "SS" },
    { name: "无比", type: "BB" },
    { name: "普利茅斯", type: "CA" },
    { name: "德鲁伊", type: "DD" },
    { name: "大胆", type: "CV" },
    { name: "蒙茅斯", type: "CA" },
    { name: "防卫", type: "CA" },
    { name: "马耳他", type: "CV" },
    { name: "哥利亚", type: "CA" },
    { name: "雷神", type: "BB" },
    { name: "海豹", type: "SS" },
    { name: "直布罗陀", type: "CA" },
    { name: "彼得罗巴甫洛夫斯克", type: "CA" },
    { name: "K-1", type: "SS" },
    { name: "哈巴罗夫斯克", type: "DD" },
    { name: "斯大林格勒", type: "CA" },
    { name: "塞瓦斯托波尔", type: "CA" },
    { name: "莫斯科", type: "CA" },
    { name: "雷暴", type: "DD" },
    { name: "光荣", type: "BB" },
    { name: "克里姆林", type: "BB" },
    { name: "科米萨尔", type: "CA" },
    { name: "德尔尼", type: "DD" },
    { name: "纳希莫夫", type: "CV" },
    { name: "亚历山大·涅夫斯基", type: "CA" },
    { name: "斯摩棱斯克", type: "CA" },
    { name: "兴登堡", type: "CA" },
    { name: "大选帝侯", type: "BB" },
    { name: "U-4501", type: "SS" },
    { name: "埃尔宾", type: "DD" },
    { name: "Z-42", type: "DD" },
    { name: "施里芬", type: "BB" },
    { name: "U-2501", type: "SS" },
    { name: "希尔德布兰德", type: "CA" },
    { name: "M.里希特霍芬", type: "CV" },
    { name: "Z-52", type: "DD" },
    { name: "格奥尔格·霍夫曼", type: "DD" },
    { name: "梅克伦堡", type: "BB" },
    { name: "马克斯·股麦曼", type: "CV" },
    { name: "普鲁士", type: "BB" },
    { name: "共和国", type: "BB" },
    { name: "卡萨尔", type: "DD" },
    { name: "马赛", type: "CA" },
    { name: "科尔伯特", type: "CA" },
    { name: "克莱贝尔", type: "DD" },
    { name: "勃艮第", type: "BB" },
    { name: "布伦努斯", type: "CA" },
    { name: "亨利四世", type: "CA" },
    { name: "玛索", type: "DD" },
    { name: "斯维亚", type: "CA" },
    { name: "斯莫兰", type: "DD" },
    { name: "格但斯克", type: "DD" },
    { name: "朗纳尔", type: "DD" },
    { name: "哈兰", type: "DD" },
    { name: "阿蒂略·莱戈洛", type: "DD" },
    { name: "威尼斯", type: "CA" },
    { name: "阿尔贝里科·达·巴尔比亚诺", type: "DD" },
    { name: "鲁杰罗·迪·劳里亚", type: "BB" },
    { name: "克里斯托弗·哥伦布", type: "BB" },
    { name: "那不勒斯", type: "CA" },
    { name: "吸血鬼II", type: "DD" },
    { name: "刻耳柏洛斯", type: "CA" },
    { name: "西西里", type: "BB" },
    { name: "布里斯班", type: "CA" },
    { name: "金狮", type: "CA" },
    { name: "岳阳", type: "DD" },
    { name: "特龙普", type: "DD" },
    { name: "济南", type: "CA" },
    { name: "奥兰治亲王", type: "CA" },
    { name: "拉潘帕", type: "DD" },
    { name: "圣马丁", type: "CA" },
    { name: "阿尔瓦罗·德·巴赞", type: "DD" },
    { name: "仁川", type: "CA" },
    { name: "旅顺", type: "DD" },
    { name: "自由", type: "DD" },
    { name: "乌特勒支", type: "CA" },
    { name: "卡斯蒂利亚", type: "CA" },
    { name: "威廉一世", type: "BB" },
    { name: "无阻", type: "BB" },
    { name: "拉蒂格海军上将", type: "CA" },
    { name: "拉菲", type: "DD" },
    { name: "阿罗娜的小鲸鱼", type: "SS" },
    { name: "西伯利亚", type: "BB" },
    { name: "大和魁", type: "BB" },
    { name: "钏路", type: "CA" },
    { name: "阿达尔伯特亲王", type: "CA" },
    { name: "夏威夷", type: "CA" },
    { name: "不来梅", type: "CA" },
    { name: "安艺", type: "BB" },
  ]
};

// 默认使用英文舰船数据
export const DEFAULT_SHIPS = SHIPS_DATA.en;
