// 多语言舰船数据
//
// Each entry below carries its own `zh` + `en` names plus shared metadata —
// single source of truth, no parallel-array invariant. The exported
// SHIPS_DATA.zh / SHIPS_DATA.en views are derived from SHIPS at the bottom
// of this file, so main.js can keep using the { en: [...], zh: [...] }
// shape unchanged.
//
// Tags (any subset, all optional):
//   "easy"    — 轮椅, forgiving; average damage from average play
//   "winning" — shapes the battlefield (most CVs, top DDs, radar boats)
//   "fun"     — memorable / gimmicky / enjoyable to play
//   "trash"   — struggles to perform, frustrating
//
// Tags below were seeded from training-data knowledge of T10 meta and
// will need manual correction. Unflagged = no strong opinion / average.
//
// premium: true 表示金币船 (coal/steel/lootbox/doubloon ships). Omit the
// field for tech-tree ships — undefined and false are equivalent.
//
// Nation codes are canonical Chinese strings — see NATIONS below. UI
// translates them at render time via translations[lang].nations in main.js.
//
// Tiers: 8 | 9 | 10 | 11.
//
// Nations marked /* ? */ are best-effort guesses pending in-game verification.

export const TIERS = [8, 9, 10, 11];

export const NATIONS = [
  "美国",
  "苏联",
  "德国",
  "日本",
  "英国",
  "法国",
  "意大利",
  "泛亚",
  "泛美",
  "英联邦",
  "泛欧",
  "荷兰",
  "西班牙",
];

const SHIPS = [
  // ── T10 ─────────────────────────────────────────────────────────
  {
    zh: "岛风",
    en: "Shimakaze",
    type: "DD",
    tier: 10,
    nation: "日本",
    tags: ["fun"],
  },
  {
    zh: "春云",
    en: "Harugumo",
    type: "DD",
    tier: 10,
    nation: "日本",
    tags: ["easy"],
  },
  {
    zh: "疾风",
    en: "Hayate",
    type: "DD",
    tier: 10,
    nation: "日本",
    premium: true,
  },
  { zh: "大和", en: "Yamato", type: "BB", tier: 10, nation: "日本" },
  {
    zh: "敷岛",
    en: "Shikishima",
    type: "BB",
    tier: 10,
    nation: "日本",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "丰后",
    en: "Bungo",
    type: "BB",
    tier: 10,
    nation: "日本",
    tags: ["easy"],
  },
  {
    zh: "吉野",
    en: "Yoshino",
    type: "CA",
    tier: 10,
    nation: "日本",
    premium: true,
  },
  {
    zh: "北上",
    en: "Kitakami",
    type: "CA",
    tier: 10,
    nation: "日本",
    tags: ["fun"],
    premium: true,
  },
  { zh: "藏王", en: "Zao", type: "CA", tier: 10, nation: "日本" },
  {
    zh: "淀",
    en: "Yodo",
    type: "CA",
    tier: 10,
    nation: "日本",
    tags: ["trash"],
  },
  { zh: "白龙", en: "Hakuryu", type: "CV", tier: 10, nation: "日本" },
  {
    zh: "信浓",
    en: "Shinano",
    type: "CV",
    tier: 10,
    nation: "日本",
    tags: ["winning", "easy"],
    premium: true,
  },
  { zh: "蒙大拿", en: "Montana", type: "BB", tier: 10, nation: "美国" },
  { zh: "佛蒙特", en: "Vermont", type: "BB", tier: 10, nation: "美国" },
  { zh: "路易斯安那", en: "Louisiana", type: "BB", tier: 10, nation: "美国" },
  {
    zh: "威斯康星",
    en: "Wisconsin",
    type: "BB",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "罗德岛",
    en: "Rhode Island",
    type: "BB",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "俄亥俄",
    en: "Ohio",
    type: "BB",
    tier: 10,
    nation: "美国",
    premium: true,
  },
  {
    zh: "得梅因",
    en: "Des Moines",
    type: "CA",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
  },
  {
    zh: "伍斯特",
    en: "Worcester",
    type: "CA",
    tier: 10,
    nation: "美国",
    tags: ["trash"],
  },
  {
    zh: "塞勒姆",
    en: "Salem",
    type: "CA",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "奥斯汀",
    en: "Austin",
    type: "CA",
    tier: 10,
    nation: "美国",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "波多黎各",
    en: "Puerto Rico",
    type: "CA",
    tier: 10,
    nation: "美国",
    premium: true,
  },
  { zh: "基林", en: "Gearing", type: "DD", tier: 10, nation: "美国" },
  {
    zh: "赫尔",
    en: "Hull",
    type: "DD",
    tier: 10,
    nation: "美国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "福雷斯特·谢尔曼",
    en: "Forrest Sherman",
    type: "DD",
    tier: 10,
    nation: "美国",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "萨默斯",
    en: "Somers",
    type: "DD",
    tier: 10,
    nation: "美国",
    premium: true,
  },
  {
    zh: "中途岛",
    en: "Midway",
    type: "CV",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
  },
  {
    zh: "埃塞克斯",
    en: "Essex",
    type: "CV",
    tier: 10,
    nation: "美国",
    tags: ["winning", "easy"],
  },
  {
    zh: "富兰克林·罗斯福",
    en: "Franklin D. Roosevelt",
    type: "CV",
    tier: 10,
    nation: "美国",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "巴劳鱵",
    en: "Balao",
    type: "SS",
    tier: 10,
    nation: "美国",
    tags: ["winning", "easy"],
  },
  {
    zh: "猫鲨",
    en: "Gato",
    type: "SS",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "射水鱼",
    en: "Archerfish",
    type: "SS",
    tier: 10,
    nation: "美国",
    tags: ["winning", "easy"],
    premium: true,
  },
  {
    zh: "米诺陶",
    en: "Minotaur",
    type: "CA",
    tier: 10,
    nation: "英国",
    tags: ["fun"],
  },
  {
    zh: "果敢",
    en: "Daring",
    type: "DD",
    tier: 10,
    nation: "英国",
    tags: ["winning"],
  },
  { zh: "圣文森特", en: "St. Vincent", type: "BB", tier: 10, nation: "英国" },
  {
    zh: "征服者",
    en: "Conqueror",
    type: "BB",
    tier: 10,
    nation: "英国",
    tags: ["easy"],
  },
  { zh: "连枷", en: "Thrasher", type: "SS", tier: 10, nation: "英国" },
  {
    zh: "无比",
    en: "Incomparable",
    type: "BB",
    tier: 10,
    nation: "英国",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "普利茅斯",
    en: "Plymouth",
    type: "CA",
    tier: 10,
    nation: "英国",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "德鲁伊",
    en: "Druid",
    type: "DD",
    tier: 10,
    nation: "英国",
    premium: true,
  },
  {
    zh: "大胆",
    en: "Audacious",
    type: "CV",
    tier: 10,
    nation: "英国",
    tags: ["trash"],
  },
  {
    zh: "蒙茅斯",
    en: "Monmouth",
    type: "CA",
    tier: 10,
    nation: "英国",
    premium: true,
  },
  {
    zh: "防卫",
    en: "Defense",
    type: "CA",
    tier: 10,
    nation: "英国",
    premium: true,
  },
  {
    zh: "马耳他",
    en: "Malta",
    type: "CV",
    tier: 10,
    nation: "英国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "哥利亚",
    en: "Goliath",
    type: "CA",
    tier: 10,
    nation: "英国",
    tags: ["trash"],
  },
  {
    zh: "雷神",
    en: "Thunderer",
    type: "BB",
    tier: 10,
    nation: "英国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "海豹",
    en: "Seal",
    type: "SS",
    tier: 10,
    nation: "英国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "直布罗陀",
    en: "Gibraltar",
    type: "CA",
    tier: 10,
    nation: "英国",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "彼得罗巴甫洛夫斯克",
    en: "Petropavlovsk",
    type: "CA",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
  },
  {
    zh: "K-1",
    en: "K-1",
    type: "SS",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
  },
  {
    zh: "哈巴罗夫斯克",
    en: "Khabarovsk",
    type: "DD",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "斯大林格勒",
    en: "Stalingrad",
    type: "CA",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "塞瓦斯托波尔",
    en: "Sevastopol",
    type: "CA",
    tier: 10,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "莫斯科",
    en: "Moskva",
    type: "CA",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
    premium: true,
  },
  { zh: "雷暴", en: "Grozovoi", type: "DD", tier: 10, nation: "苏联" },
  {
    zh: "光荣",
    en: "Slava",
    type: "BB",
    tier: 10,
    nation: "苏联",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "克里姆林",
    en: "Kremlin",
    type: "BB",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
  },
  {
    zh: "科米萨尔",
    en: "Komissar",
    type: "CA",
    tier: 10,
    nation: "苏联",
    premium: true,
  },
  { zh: "德尔尼", en: "Delny", type: "DD", tier: 10, nation: "苏联" },
  {
    zh: "纳希莫夫",
    en: "Nakhimov",
    type: "CV",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
  },
  {
    zh: "亚历山大·涅夫斯基",
    en: "Alexander Nevsky",
    type: "CA",
    tier: 10,
    nation: "苏联",
  },
  {
    zh: "斯摩棱斯克",
    en: "Smolensk",
    type: "CA",
    tier: 10,
    nation: "苏联",
    tags: ["fun"],
    premium: true,
  },
  { zh: "兴登堡", en: "Hindenburg", type: "CA", tier: 10, nation: "德国" },
  {
    zh: "大选帝侯",
    en: "Grosser Kurfürst",
    type: "BB",
    tier: 10,
    nation: "德国",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "U-4501",
    en: "U-4501",
    type: "SS",
    tier: 10,
    nation: "德国",
    tags: ["easy", "winning"],
    premium: true,
  },
  {
    zh: "埃尔宾",
    en: "Elbing",
    type: "DD",
    tier: 10,
    nation: "德国",
    tags: ["fun"],
  },
  {
    zh: "Z-42",
    en: "Z-42",
    type: "DD",
    tier: 10,
    nation: "德国",
    tags: ["winning"],
  },
  {
    zh: "施里芬",
    en: "Schlieffen",
    type: "BB",
    tier: 10,
    nation: "德国",
    tags: ["fun"],
  },
  {
    zh: "U-2501",
    en: "U-2501",
    type: "SS",
    tier: 10,
    nation: "德国",
    tags: ["easy", "winning"],
  },
  {
    zh: "希尔德布兰德",
    en: "Hildebrand",
    type: "CA",
    tier: 10,
    nation: "德国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "M.里希特霍芬",
    en: "M. Richthofen",
    type: "CV",
    tier: 10,
    nation: "德国",
    tags: ["winning"],
  },
  {
    zh: "Z-52",
    en: "Z-52",
    type: "DD",
    tier: 10,
    nation: "德国",
    tags: ["winning"],
  },
  {
    zh: "格奥尔格·霍夫曼",
    en: "Georg Hoffman",
    type: "DD",
    tier: 10,
    nation: "德国",
    premium: true,
  },
  {
    zh: "梅克伦堡",
    en: "Mecklenburg",
    type: "BB",
    tier: 10,
    nation: "德国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "马克斯·股麦曼",
    en: "Max Immelmann",
    type: "CV",
    tier: 10,
    nation: "德国",
    tags: ["winning"],
    premium: true,
  },
  { zh: "普鲁士", en: "Preussen", type: "BB", tier: 10, nation: "德国" },
  { zh: "共和国", en: "Republique", type: "BB", tier: 10, nation: "法国" },
  { zh: "卡萨尔", en: "Cassard", type: "DD", tier: 10, nation: "法国" },
  {
    zh: "马赛",
    en: "Marseille",
    type: "CA",
    tier: 10,
    nation: "法国",
    tags: ["winning"],
  },
  {
    zh: "科尔伯特",
    en: "Colbert",
    type: "CA",
    tier: 10,
    nation: "法国",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "克莱贝尔",
    en: "Kleber",
    type: "DD",
    tier: 10,
    nation: "法国",
    tags: ["fun", "winning"],
  },
  {
    zh: "勃艮第",
    en: "Bourgogne",
    type: "BB",
    tier: 10,
    nation: "法国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "布伦努斯",
    en: "Brennus",
    type: "CA",
    tier: 10,
    nation: "法国",
    tags: ["easy"],
    premium: true,
  },
  { zh: "亨利四世", en: "Henri IV", type: "CA", tier: 10, nation: "法国" },
  {
    zh: "玛索",
    en: "Marceau",
    type: "DD",
    tier: 10,
    nation: "法国",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "斯维亚",
    en: "Svea",
    type: "CA",
    tier: 10,
    nation: "泛欧",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "斯莫兰",
    en: "Småland",
    type: "DD",
    tier: 10,
    nation: "泛欧",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "格但斯克",
    en: "Gdansk",
    type: "DD",
    tier: 10,
    nation: "泛欧",
    tags: ["winning"],
  },
  {
    zh: "朗纳尔",
    en: "Ragnar",
    type: "DD",
    tier: 10,
    nation: "泛欧",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "哈兰",
    en: "Halland",
    type: "DD",
    tier: 10,
    nation: "泛欧",
    tags: ["winning"],
  },
  {
    zh: "阿蒂略·莱戈洛",
    en: "Attilio Regolo",
    type: "DD",
    tier: 10,
    nation: "意大利",
    tags: ["fun"],
  },
  {
    zh: "威尼斯",
    en: "Venezia",
    type: "CA",
    tier: 10,
    nation: "意大利",
    tags: ["easy"],
  },
  {
    zh: "阿尔贝里科·达·巴尔比亚诺",
    en: "Alberico da Barbiano",
    type: "DD",
    tier: 10,
    nation: "意大利",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "鲁杰罗·迪·劳里亚",
    en: "Ruggiero di Lauria",
    type: "BB",
    tier: 10,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "克里斯托弗·哥伦布",
    en: "Cristoforo Colombo",
    type: "BB",
    tier: 10,
    nation: "意大利",
    tags: ["easy"],
  },
  {
    zh: "那不勒斯",
    en: "Napoli",
    type: "CA",
    tier: 10,
    nation: "意大利",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "吸血鬼II",
    en: "Vampire II",
    type: "DD",
    tier: 10,
    nation: "英联邦",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "刻耳柏洛斯",
    en: "Cerberus",
    type: "CA",
    tier: 10,
    nation: "英联邦" /* ? */,
  },
  {
    zh: "西西里",
    en: "Sicilia",
    type: "BB",
    tier: 10,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "布里斯班",
    en: "Brisbane",
    type: "CA",
    tier: 10,
    nation: "英联邦",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "金狮",
    en: "Gouden Leeuw",
    type: "CA",
    tier: 10,
    nation: "荷兰",
    tags: ["fun"],
  },
  { zh: "岳阳", en: "Yueyang", type: "DD", tier: 10, nation: "泛亚" },
  {
    zh: "特龙普",
    en: "Tromp",
    type: "DD",
    tier: 10,
    nation: "荷兰",
    tags: ["fun"],
    premium: true,
  },
  {
    zh: "济南",
    en: "Jinan",
    type: "CA",
    tier: 10,
    nation: "泛亚",
    tags: ["fun"],
  },
  {
    zh: "奥兰治亲王",
    en: "Prins van Oranje",
    type: "CA",
    tier: 10,
    nation: "荷兰",
    premium: true,
  },
  {
    zh: "拉潘帕",
    en: "La Pampa",
    type: "DD",
    tier: 10,
    nation: "泛美",
    premium: true,
  },
  {
    zh: "圣马丁",
    en: "San Martín",
    type: "CA",
    tier: 10,
    nation: "泛美",
    tags: ["winning"],
  },
  {
    zh: "阿尔瓦罗·德·巴赞",
    en: "Álvaro de Bazán",
    type: "DD",
    tier: 10,
    nation: "西班牙",
    premium: true,
  },
  {
    zh: "仁川",
    en: "Incheon",
    type: "CA",
    tier: 10,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "旅顺",
    en: "Lüshun",
    type: "DD",
    tier: 10,
    nation: "泛亚",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "自由",
    en: "Libertad",
    type: "BB",
    tier: 10,
    nation: "泛美",
    tags: ["easy", "winning"],
  },
  { zh: "乌特勒支", en: "Utrecht", type: "CA", tier: 10, nation: "荷兰" },
  { zh: "卡斯蒂利亚", en: "Castilla", type: "CA", tier: 10, nation: "西班牙" },
  {
    zh: "威廉一世",
    en: "Willem de Eerste",
    type: "BB",
    tier: 10,
    nation: "荷兰",
    premium: true,
  },
  {
    zh: "无阻",
    en: "Irresistible",
    type: "BB",
    tier: 10,
    nation: "英国",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "拉蒂格上将",
    en: "Admiral Latgé",
    type: "CA",
    tier: 10,
    nation: "法国",
    premium: true,
  },
  {
    zh: "拉菲",
    en: "Laffey",
    type: "DD",
    tier: 10,
    nation: "美国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "西伯利亚",
    en: "Siberia",
    type: "BB",
    tier: 10,
    nation: "苏联",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "钏路",
    en: "Kushiro",
    type: "CA",
    tier: 10,
    nation: "日本",
    tags: ["trash"],
    premium: true,
  },
  {
    zh: "阿达尔伯特亲王",
    en: "Prinz Adalbert",
    type: "CA",
    tier: 10,
    nation: "德国",
  },
  {
    zh: "夏威夷",
    en: "Hawaii",
    type: "CA",
    tier: 10,
    nation: "美国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "不来梅",
    en: "Bremen",
    type: "CA",
    tier: 10,
    nation: "德国",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "安艺",
    en: "Aki",
    type: "BB",
    tier: 10,
    nation: "日本",
    premium: true,
  },
  {
    zh: "金枪鱼",
    en: "Tonijn",
    type: "SS",
    tier: 10,
    nation: "荷兰",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "絮库夫",
    en: "Surcouf",
    type: "SS",
    tier: 10,
    nation: "法国",
    premium: true,
  },
  { zh: "托尔", en: "Thor", type: "BB", tier: 10, nation: "泛欧" /* ? */ },
  {
    zh: "自主",
    en: "Independencia",
    type: "CV",
    tier: 10,
    nation: "泛美" /* ? */,
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "先驱",
    en: "Pioneer",
    type: "CA",
    tier: 10,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "雷诺堡",
    en: "Châteaurenault",
    type: "DD",
    tier: 10,
    nation: "法国",
    premium: true,
  },
  {
    zh: "海洋",
    en: "Ocean",
    type: "CV",
    tier: 10,
    nation: "英国",
    tags: ["winning"],
    premium: true,
  },
  {
    zh: "伊-56 44",
    en: "I-56 44",
    type: "SS",
    tier: 10,
    nation: "日本",
    tags: ["easy"],
    premium: true,
  },
  {
    zh: "布洛士",
    en: "Burrows",
    type: "DD",
    tier: 10,
    nation: "美国",
    tags: ["trash"],
  },

  // ── T9 ──────────────────────────────────────────────────────────
  {
    zh: "天津",
    en: "Tianjin",
    type: "CA",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "载之",
    en: "Zai Zhi",
    type: "BB",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  { zh: "罗恩", en: "Roon", type: "CA", tier: 9, nation: "德国" },
  {
    zh: "弗里斯兰",
    en: "Friesland",
    type: "DD",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "耶格尔",
    en: "Jäger",
    type: "DD",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "太行",
    en: "Taihang",
    type: "BB",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "吾妻",
    en: "Azuma",
    type: "CA",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  { zh: "邓肯", en: "Duncan", type: "BB", tier: 9, nation: "英国" },
  {
    zh: "格罗宁根",
    en: "Groningen",
    type: "DD",
    tier: 9,
    nation: "荷兰",
    premium: true,
  },
  {
    zh: "AL苏维埃罗西亚",
    en: "AL Sovetskaya Rossiya",
    type: "BB",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "布莱克",
    en: "Black",
    type: "DD",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "瓦列霍",
    en: "Vallejo",
    type: "CA",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  { zh: "弗莱彻", en: "Fletcher", type: "DD", tier: 9, nation: "美国" },
  { zh: "桑坦德", en: "Santander", type: "CA", tier: 9, nation: "泛美" },
  { zh: "布林迪西", en: "Brindisi", type: "CA", tier: 9, nation: "意大利" },
  { zh: "路易九世", en: "Saint-Louis", type: "CA", tier: 9, nation: "法国" },
  { zh: "莫加多尔", en: "Mogador", type: "DD", tier: 9, nation: "法国" },
  {
    zh: "猩红雷霆",
    en: "Scarlet Thunder",
    type: "BB",
    tier: 9,
    nation: "英国",
    premium: true,
  },
  {
    zh: "闪电52",
    en: "Błyskawica 52",
    type: "DD",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "尼奥尔德",
    en: "Njord",
    type: "BB",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "迪米特里-顿斯科伊",
    en: "Dmitri Donskoi",
    type: "CA",
    tier: 9,
    nation: "苏联",
  },
  {
    zh: "鲁西永",
    en: "Roussillon",
    type: "BB",
    tier: 9,
    nation: "法国",
    premium: true,
  },
  { zh: "安第斯", en: "Andes", type: "BB", tier: 9, nation: "泛美" },
  {
    zh: "约翰斯顿",
    en: "Johnston",
    type: "DD",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  { zh: "北风", en: "Kitakaze", type: "DD", tier: 9, nation: "日本" },
  {
    zh: "大连",
    en: "Dalian",
    type: "CA",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  { zh: "出云", en: "Izumo", type: "BB", tier: 9, nation: "日本" },
  {
    zh: "埃吉尔",
    en: "Ägir",
    type: "CA",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "南宁",
    en: "Nanning",
    type: "DD",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "苏联",
    en: "Sovetsky Soyuz",
    type: "BB",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "索姆河",
    en: "Somme",
    type: "DD",
    tier: 9,
    nation: "英国",
    premium: true,
  },
  {
    zh: "勒阿弗尔",
    en: "Le Havre",
    type: "CA",
    tier: 9,
    nation: "法国",
    premium: true,
  },
  {
    zh: "肥前",
    en: "Hizen",
    type: "BB",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "剑桥",
    en: "Cambridge",
    type: "CA",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "ZF-6",
    en: "ZF-6",
    type: "DD",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "奥肯多海军上将",
    en: "Admiral Oquendo",
    type: "CA",
    tier: 9,
    nation: "西班牙",
    premium: true,
  },
  {
    zh: "印第安纳",
    en: "Indiana",
    type: "BB",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  { zh: "克里斯托弗", en: "Christopher", type: "DD", tier: 9, nation: "美国" },
  {
    zh: "沂蒙",
    en: "Yimeng",
    type: "BB",
    tier: 9,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "铃谷",
    en: "Suzuya",
    type: "CA",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "布吕歇尔",
    en: "Blücher",
    type: "CA",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "ZH-1",
    en: "ZH-1",
    type: "DD",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "Z-44",
    en: "Z-44",
    type: "DD",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "库兹马·米宁",
    en: "Kuzma Minin",
    type: "CA",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  { zh: "西雅图", en: "Seattle", type: "CA", tier: 9, nation: "美国" },
  {
    zh: "门诺·范库霍恩",
    en: "Menno van Coehoorn",
    type: "CA",
    tier: 9,
    nation: "荷兰",
  },
  { zh: "马尔博罗", en: "Marlborough", type: "BB", tier: 9, nation: "英国" },
  {
    zh: "墨西拿",
    en: "Messina",
    type: "CA",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "瓦尔帕莱索",
    en: "Valparaíso",
    type: "BB",
    tier: 9,
    nation: "泛美",
    premium: true,
  },
  {
    zh: "卡诺",
    en: "Carnot",
    type: "CA",
    tier: 9,
    nation: "法国",
    premium: true,
  },
  {
    zh: "剑",
    en: "Tsurugi",
    type: "BB",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  { zh: "明尼苏达", en: "Minnesota", type: "BB", tier: 9, nation: "美国" },
  { zh: "范·斯佩克", en: "Van Speyk", type: "CA", tier: 9, nation: "荷兰" },
  {
    zh: "纳瓦林",
    en: "Navarin",
    type: "BB",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  { zh: "乌达洛伊", en: "Udaloi", type: "DD", tier: 9, nation: "苏联" },
  { zh: "东约特兰", en: "Östergötland", type: "DD", tier: 9, nation: "泛欧" },
  { zh: "里加", en: "Riga", type: "CA", tier: 9, nation: "苏联" },
  { zh: "日德兰", en: "Jutland", type: "DD", tier: 9, nation: "英国" },
  { zh: "狮", en: "Lion", type: "BB", tier: 9, nation: "英国" },
  {
    zh: "米开朗基罗",
    en: "Michelangelo",
    type: "CA",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "石见",
    en: "Iwami",
    type: "BB",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  { zh: "遭遇", en: "Encounter", type: "CA", tier: 9, nation: "英联邦" },
  { zh: "依阿华", en: "Iowa", type: "BB", tier: 9, nation: "美国" },
  {
    zh: "菲利克斯·舒尔茨",
    en: "Felix Schultz",
    type: "DD",
    tier: 9,
    nation: "德国",
  },
  {
    zh: "马可波罗",
    en: "Marco Polo",
    type: "BB",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  { zh: "夕云", en: "Yūgumo", type: "DD", tier: 9, nation: "日本" },
  { zh: "安达卢西亚", en: "Andalucía", type: "CA", tier: 9, nation: "西班牙" },
  { zh: "忠武", en: "Chungmu", type: "DD", tier: 9, nation: "泛亚" },
  {
    zh: "腓特烈大帝",
    en: "Friedrich der Grosse",
    type: "BB",
    tier: 9,
    nation: "德国",
  },
  {
    zh: "密苏里",
    en: "Missouri",
    type: "BB",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "贝纳姆",
    en: "Benham",
    type: "DD",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  { zh: "塔什干", en: "Tashkent", type: "DD", tier: 9, nation: "苏联" },
  { zh: "亚得里亚", en: "Adriatico", type: "DD", tier: 9, nation: "意大利" },
  { zh: "高梁", en: "Takahashi", type: "CA", tier: 9, nation: "日本" },
  {
    zh: "峰云",
    en: "Minekaze",
    type: "DD",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "维多利亚",
    en: "Victoria",
    type: "BB",
    tier: 9,
    nation: "西班牙",
    premium: true,
  },
  {
    zh: "佐治亚",
    en: "Georgia",
    type: "BB",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "鲁普雷希特亲王",
    en: "Prinz Rupprecht",
    type: "BB",
    tier: 9,
    nation: "德国",
  },
  { zh: "特拉华", en: "Delaware", type: "BB", tier: 9, nation: "美国" },
  {
    zh: "齐格菲",
    en: "Siegfried",
    type: "CA",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "哈尔福德",
    en: "Halford",
    type: "DD",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "施罗德",
    en: "Schröder",
    type: "CA",
    tier: 9,
    nation: "德国",
    premium: true,
  },
  {
    zh: "保罗·埃米利奥",
    en: "Paolo Emilio",
    type: "DD",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  { zh: "水牛城", en: "Buffalo", type: "CA", tier: 9, nation: "美国" },
  {
    zh: "卡尔十四世·约翰",
    en: "Karl XIV Johan",
    type: "BB",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  {
    zh: "武藏",
    en: "Musashi",
    type: "BB",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "阿伯丁",
    en: "Aberdeen",
    type: "CA",
    tier: 9,
    nation: "英国",
    premium: true,
  },
  { zh: "布雷斯特", en: "Brest", type: "CA", tier: 9, nation: "法国" },
  { zh: "曼陀菲尔", en: "Manteuffel", type: "CA", tier: 9, nation: "德国" },
  { zh: "伊吹", en: "Ibuki", type: "CA", tier: 9, nation: "日本" },
  {
    zh: "兰布罗斯·卡措尼斯",
    en: "Lambros Katsonis",
    type: "DD",
    tier: 9,
    nation: "泛欧",
  },
  { zh: "Z-46", en: "Z-46", type: "DD", tier: 9, nation: "德国" },
  { zh: "古斯塔夫大帝", en: "Gustav", type: "BB", tier: 9, nation: "泛欧" },
  {
    zh: "筑摩II",
    en: "Chikuma II",
    type: "CA",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "赫克托耳",
    en: "Hector",
    type: "CA",
    tier: 9,
    nation: "英联邦",
    premium: true,
  },
  {
    zh: "巴夫勒尔",
    en: "Barfleur",
    type: "DD",
    tier: 9,
    nation: "英国",
    premium: true,
  },
  { zh: "世宗", en: "Sejong", type: "CA", tier: 9, nation: "泛亚" },
  {
    zh: "费兰特·贡扎加",
    en: "Ferrante Gonzaga",
    type: "CA",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "阿拉斯加",
    en: "Alaska",
    type: "CA",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "让·巴尔",
    en: "Jean Bart",
    type: "BB",
    tier: 9,
    nation: "法国",
    premium: true,
  },
  {
    zh: "大山",
    en: "Daisen",
    type: "BB",
    tier: 9,
    nation: "日本",
    premium: true,
  },
  {
    zh: "伊利诺伊",
    en: "Illinois",
    type: "BB",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "奇尔沙治",
    en: "Kearsarge",
    type: "BB",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "约翰·德·维特",
    en: "Johan de Witt",
    type: "CA",
    tier: 9,
    nation: "荷兰",
  },
  { zh: "安达太良", en: "Adatara", type: "BB", tier: 9, nation: "日本" },
  { zh: "阿尔萨斯", en: "Alsace", type: "BB", tier: 9, nation: "法国" },
  {
    zh: "不惧",
    en: "Neustrashimy",
    type: "DD",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "贝洛斯",
    en: "Velos",
    type: "DD",
    tier: 9,
    nation: "泛欧",
    premium: true,
  },
  { zh: "德雷克", en: "Drake", type: "CA", tier: 9, nation: "英国" },
  { zh: "涅普顿", en: "Neptune", type: "CA", tier: 9, nation: "英国" },
  {
    zh: "喀琅施塔得",
    en: "Kronshtadt",
    type: "CA",
    tier: 9,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "朱塞佩·威尔第",
    en: "Giuseppe Verdi",
    type: "BB",
    tier: 9,
    nation: "意大利",
    premium: true,
  },
  { zh: "暴风雨", en: "Orage", type: "DD", tier: 9, nation: "法国" },
  { zh: "勒班陀", en: "Lepanto", type: "BB", tier: 9, nation: "意大利" },
  {
    zh: "塔尔萨",
    en: "Tulsa",
    type: "CA",
    tier: 9,
    nation: "美国",
    premium: true,
  },
  {
    zh: "波美拉尼亚",
    en: "Pommern",
    type: "BB",
    tier: 9,
    nation: "德国",
    premium: true,
  },

  // ── T8 ──────────────────────────────────────────────────────────
  {
    zh: "企业",
    en: "Enterprise",
    type: "CV",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "奥恰科夫",
    en: "Ochakov",
    type: "CA",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "威奇塔",
    en: "Wichita",
    type: "CA",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "田纳西",
    en: "Tennessee",
    type: "BB",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "契卡洛夫",
    en: "Chkalov",
    type: "CV",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "基德",
    en: "Kidd",
    type: "DD",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  { zh: "阳炎", en: "Kagero", type: "DD", tier: 8, nation: "日本" },
  {
    zh: "罗彻斯特",
    en: "Rochester",
    type: "CA",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "博罗季诺",
    en: "Borodino",
    type: "BB",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "灵巧",
    en: "Ognevoi",
    type: "DD",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "安克雷奇",
    en: "Anchorage",
    type: "CA",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "罗马",
    en: "Roma",
    type: "BB",
    tier: 8,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "爱宕",
    en: "Atago",
    type: "CA",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  {
    zh: "大黄蜂",
    en: "Hornet",
    type: "CV",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "米哈伊尔·库图佐夫",
    en: "Mikhail Kutuzov",
    type: "CA",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  { zh: "霍克", en: "Hawke", type: "BB", tier: 8, nation: "英国" },
  { zh: "奥克兰", en: "Auckland", type: "CA", tier: 8, nation: "英联邦" },
  {
    zh: "阿拉巴马",
    en: "Alabama",
    type: "BB",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  { zh: "爱丁堡", en: "Edinburgh", type: "CA", tier: 8, nation: "英国" },
  {
    zh: "前卫",
    en: "Vanguard",
    type: "BB",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "Z-35",
    en: "Z-35",
    type: "DD",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "I-56",
    en: "I-56",
    type: "SS",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  {
    zh: "利根",
    en: "Tone",
    type: "CA",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  { zh: "最上", en: "Mogami", type: "CA", tier: 8, nation: "日本" },
  {
    zh: "希佩尔上将",
    en: "Admiral Hipper",
    type: "CA",
    tier: 8,
    nation: "德国",
  },
  {
    zh: "彼得罗·巴格拉季昂",
    en: "Pyotr Bagration",
    type: "CA",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "大西洋",
    en: "Atlántico",
    type: "BB",
    tier: 8,
    nation: "泛美",
    premium: true,
  },
  { zh: "Z-23", en: "Z-23", type: "DD", tier: 8, nation: "德国" },
  {
    zh: "汾阳",
    en: "Fenyang",
    type: "DD",
    tier: 8,
    nation: "泛亚",
    premium: true,
  },
  { zh: "翔鹤", en: "Shokaku", type: "CV", tier: 8, nation: "日本" },
  {
    zh: "勃兰登堡",
    en: "Brandenburg",
    type: "BB",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "时雨",
    en: "Shigure",
    type: "DD",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  { zh: "塔林", en: "Tallinn", type: "CA", tier: 8, nation: "苏联" },
  { zh: "克利夫兰", en: "Cleveland", type: "CA", tier: 8, nation: "美国" },
  { zh: "奥斯本", en: "Osborne", type: "DD", tier: 8, nation: "美国" },
  { zh: "黎塞留", en: "Richelieu", type: "BB", tier: 8, nation: "法国" },
  { zh: "列克星敦", en: "Lexington", type: "CV", tier: 8, nation: "美国" },
  {
    zh: "威斯巴登",
    en: "Wiesbaden",
    type: "CA",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "格劳海军上将",
    en: "Almirante Grau",
    type: "CA",
    tier: 8,
    nation: "泛美",
    premium: true,
  },
  {
    zh: "加贺",
    en: "Kaga",
    type: "CV",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  {
    zh: "诺丁汉",
    en: "Nottingham",
    type: "CA",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "奥什",
    en: "Hoche",
    type: "DD",
    tier: 8,
    nation: "法国",
    premium: true,
  },
  {
    zh: "闪电44",
    en: "Błyskawica '44",
    type: "DD",
    tier: 8,
    nation: "泛欧",
    premium: true,
  },
  { zh: "加泰罗尼亚", en: "Cataluña", type: "CA", tier: 8, nation: "西班牙" },
  { zh: "胜利", en: "Pobeda", type: "CV", tier: 8, nation: "苏联" },
  { zh: "瑟堡", en: "Cherbourg", type: "CA", tier: 8, nation: "法国" },
  { zh: "齐滕", en: "Zieten", type: "BB", tier: 8, nation: "德国" },
  {
    zh: "爱斯基摩人",
    en: "Eskimo",
    type: "DD",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  { zh: "众志", en: "Zhongzhi" /* ? */, type: "BB", tier: 8, nation: "泛欧" },
  { zh: "内布拉斯加", en: "Nebraska", type: "BB", tier: 8, nation: "美国" },
  {
    zh: "欧根亲王",
    en: "Prinz Eugen",
    type: "CA",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "塞班",
    en: "Saipan",
    type: "CV",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "克尼塞伯克",
    en: "Knesebeck" /* ? */,
    type: "CA",
    tier: 8,
    nation: "德国",
  },
  { zh: "阿马尔菲", en: "Amalfi", type: "CA", tier: 8, nation: "意大利" },
  {
    zh: "朝潮",
    en: "Asashio",
    type: "DD",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  {
    zh: "齐柏林伯爵",
    en: "Graf Zeppelin",
    type: "CV",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "皮卡第",
    en: "Picardie",
    type: "BB",
    tier: 8,
    nation: "法国",
    premium: true,
  },
  { zh: "俾斯麦", en: "Bismarck", type: "BB", tier: 8, nation: "德国" },
  {
    zh: "柴郡",
    en: "Cheshire",
    type: "CA",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "国会",
    en: "Congress",
    type: "CA",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  { zh: "天城", en: "Amagi", type: "BB", tier: 8, nation: "日本" },
  { zh: "厄兰", en: "Öland", type: "DD", tier: 8, nation: "泛欧" },
  { zh: "强健", en: "Splendid" /* ? */, type: "SS", tier: 8, nation: "英国" },
  { zh: "U-190", en: "U-190", type: "SS", tier: 8, nation: "德国" },
  {
    zh: "HSF晴风II",
    en: "HSF Harekaze II",
    type: "DD",
    tier: 8,
    nation: "日本",
    premium: true,
  },
  { zh: "哈尔滨", en: "Harbin", type: "CA", tier: 8, nation: "泛亚" },
  {
    zh: "虎59",
    en: "Tiger '59",
    type: "CA",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  { zh: "纪伊", en: "Kii", type: "BB", tier: 8, nation: "日本", premium: true },
  {
    zh: "图尔古特·雷伊斯",
    en: "Turgut Reis",
    type: "BB",
    tier: 8,
    nation: "泛欧",
    premium: true,
  },
  { zh: "L-20", en: "L-20", type: "SS", tier: 8, nation: "苏联" },
  {
    zh: "卡罗尔一世",
    en: "Carol I",
    type: "CA",
    tier: 8,
    nation: "泛欧",
    premium: true,
  },
  { zh: "堪萨斯", en: "Kansas", type: "BB", tier: 8, nation: "美国" },
  {
    zh: "列宁",
    en: "Lenin",
    type: "BB",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  {
    zh: "贝尔法斯特43",
    en: "Belfast '43",
    type: "CA",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "可怖",
    en: "Terrible",
    type: "DD",
    tier: 8,
    nation: "法国",
    premium: true,
  },
  {
    zh: "提尔皮茨",
    en: "Tirpitz",
    type: "BB",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  {
    zh: "布里奇波特",
    en: "Bridgeport",
    type: "CA",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "联盟",
    en: "Alliance",
    type: "SS",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "马萨诸塞",
    en: "Massachusetts",
    type: "BB",
    tier: 8,
    nation: "美国",
    premium: true,
  },
  {
    zh: "天鹰",
    en: "Aquila",
    type: "CV",
    tier: 8,
    nation: "意大利",
    premium: true,
  },
  {
    zh: "不挠",
    en: "Indomitable",
    type: "CV",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  { zh: "哈勒姆", en: "Haarlem", type: "CA", tier: 8, nation: "荷兰" },
  {
    zh: "北卡罗来纳",
    en: "North Carolina",
    type: "BB",
    tier: 8,
    nation: "美国",
  },
  {
    zh: "那莱",
    en: "Naresuan" /* ? */,
    type: "CA",
    tier: 8,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "伊格纳西奥·阿连德",
    en: "Ignacio Allende",
    type: "CA",
    tier: 8,
    nation: "泛美",
  },
  {
    zh: "哥萨克人",
    en: "Cossack",
    type: "DD",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "符拉迪沃斯托克",
    en: "Vladivostok",
    type: "BB",
    tier: 8,
    nation: "苏联",
  },
  {
    zh: "奥丁",
    en: "Odin",
    type: "BB",
    tier: 8,
    nation: "德国",
    premium: true,
  },
  { zh: "四万十", en: "Shimanto", type: "CA", tier: 8, nation: "日本" },
  { zh: "冒险家", en: "Aventurier", type: "DD", tier: 8, nation: "法国" },
  {
    zh: "香槟",
    en: "Champagne",
    type: "BB",
    tier: 8,
    nation: "法国",
    premium: true,
  },
  {
    zh: "洛阳",
    en: "Loyang",
    type: "DD",
    tier: 8,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "巴格拉季昂",
    en: "Bagration" /* ? */,
    type: "CA",
    tier: 8,
    nation: "苏联",
    premium: true,
  },
  { zh: "G.J.梅克尔", en: "G.J. Meckel", type: "DD", tier: 8, nation: "德国" },
  {
    zh: "伊里安",
    en: "Irian",
    type: "CA",
    tier: 8,
    nation: "泛亚",
    premium: true,
  },
  {
    zh: "忒修斯",
    en: "Theseus",
    type: "CV",
    tier: 8,
    nation: "英国",
    premium: true,
  },
  {
    zh: "加斯科涅",
    en: "Gascogne",
    type: "BB",
    tier: 8,
    nation: "法国",
    premium: true,
  },
  {
    zh: "努曼西亚",
    en: "Numancia",
    type: "CA",
    tier: 8,
    nation: "西班牙",
    premium: true,
  },

  // ── T11 ─────────────────────────────────────────────────────────
  { zh: "新西伯利亚", en: "Novosibirsk", type: "CA", tier: 11, nation: "苏联" },
  { zh: "毁灭", en: "Devastation", type: "BB", tier: 11, nation: "英国" },
  { zh: "山雾", en: "Yamagiri", type: "DD", tier: 11, nation: "日本" },
  {
    zh: "乌沙科夫",
    en: "Admiral Ushakov",
    type: "BB",
    tier: 11,
    nation: "苏联",
  },
  { zh: "汉诺威", en: "Hannover", type: "BB", tier: 11, nation: "德国" },
  { zh: "孔代", en: "Condé", type: "CA", tier: 11, nation: "法国" },
  { zh: "祖国", en: "Patrie", type: "BB", tier: 11, nation: "法国" },
  { zh: "皮埃蒙特", en: "Piemonte", type: "CA", tier: 11, nation: "意大利" },
  { zh: "昆明", en: "Kunming", type: "DD", tier: 11, nation: "泛亚" },
  {
    zh: "杰克逊维尔",
    en: "Jacksonville",
    type: "CA",
    tier: 11,
    nation: "美国",
  },
  { zh: "缅因", en: "Maine", type: "BB", tier: 11, nation: "美国" },
  { zh: "埃德加", en: "Edgar", type: "CA", tier: 11, nation: "英国" },
  { zh: "萨摩", en: "Satsuma", type: "BB", tier: 11, nation: "日本" },
  { zh: "克劳塞维茨", en: "Clausewitz", type: "CA", tier: 11, nation: "德国" },
  { zh: "赤龙", en: "Sekiryu", type: "CV", tier: 11, nation: "日本" },
  { zh: "佐尔基", en: "Zorkiy", type: "DD", tier: 11, nation: "苏联" },
  { zh: "达拉纳", en: "Dalarna", type: "DD", tier: 11, nation: "泛欧" },
  { zh: "安纳波利斯", en: "Annapolis", type: "CA", tier: 11, nation: "美国" },
  { zh: "老鹰", en: "Eagle", type: "CV", tier: 11, nation: "英国" },
  {
    zh: "约书亚·汉弗莱斯",
    en: "Joshua Humphreys",
    type: "DD",
    tier: 11,
    nation: "美国",
  },
  { zh: "合众国", en: "United States", type: "CV", tier: 11, nation: "美国" },
];

// Derive { en: [...], zh: [...] } views from the single source above.
// main.js consumes these as parallel arrays (index alignment is guaranteed
// by construction). To rename or retag a ship, edit it in SHIPS only.
const view = (lang) =>
  SHIPS.map(({ zh, en, ...rest }) => ({
    name: lang === "zh" ? zh : en,
    ...rest,
  }));

export const SHIPS_DATA = { zh: view("zh"), en: view("en") };

// 默认使用中文舰船数据
export const DEFAULT_SHIPS = SHIPS_DATA.zh;
